### ISSUE TITLE
KeyError: 'brand'

### ISSUE THREAD

**Issue by zhaibo623** [f90/Wave-U-Net#79]
(yinpin) c:\download\Wave-U-Net-master>python Predict.py with cfg.full_multi_instrument model_path="checkpoints/full_multi_instrument/full_multi_instrument-134067" input_path="/mnt/medien/Daniel/Music/Dark Passion Play/Nightwish - Bye Bye Beautiful.mp3" output_path="/home/daniel"
Training multi-instrument separation with best model
Traceback (most recent call last):
  File "Predict.py", line 14, in <module>
    @ex.automain
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\experiment.py", line 137, in automain
    self.run_commandline()
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\experiment.py", line 260, in run_commandline
    return self.run(cmd_name, config_updates, named_configs, {}, args)
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\experiment.py", line 208, in run
    meta_info, options)
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\experiment.py", line 433, in _create_run
    None))
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\initialize.py", line 394, in create_run
    host_info = get_host_info()
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\host_info.py", line 40, in get_host_info
    host_info[k] = v()
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\host_info.py", line 95, in _cpu
    return _get_cpu_by_pycpuinfo()
  File "C:\Users\Administrator\anaconda3\envs\yinpin\lib\site-packages\sacred\host_info.py", line 159, in _get_cpu_by_pycpuinfo
    return cpuinfo.get_cpu_info()['brand']
KeyError: 'brand'

**Comment by Hanbi-Kim** [comment]
lib/site-packages/sacred/host_info.py line 159,

return cpuinfo.get_cpu_info()['brand'] -> return cpuinfo.get_cpu_info()['brand_raw']

**Comment by f90** [comment]
Looks like an issue with `sacred`, did you make sure you have `sacred==0.7.3` installed as defined in the requirements.txt?
